# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compress.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompressUI(object):
    def setupUi(self, CompressUI):
        CompressUI.setObjectName("CompressUI")
        CompressUI.resize(658, 607)
        CompressUI.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.progressBar = QtWidgets.QProgressBar(CompressUI)
        self.progressBar.setGeometry(QtCore.QRect(30, 420, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar::chunk { background-color: rgb(32, 140, 255) }\n"
"QProgressBar { text-align: right }")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.file_info = QtWidgets.QTableWidget(CompressUI)
        self.file_info.setGeometry(QtCore.QRect(20, 170, 611, 91))
        self.file_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_info.setLineWidth(3)
        self.file_info.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.file_info.setShowGrid(False)
        self.file_info.setRowCount(0)
        self.file_info.setObjectName("file_info")
        self.file_info.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(3, item)
        self.file_info.horizontalHeader().setVisible(True)
        self.file_info.horizontalHeader().setCascadingSectionResizes(False)
        self.file_info.horizontalHeader().setDefaultSectionSize(152)
        self.file_info.horizontalHeader().setMinimumSectionSize(28)
        self.file_info.verticalHeader().setVisible(False)
        self.file_info.verticalHeader().setDefaultSectionSize(45)
        self.file_info.verticalHeader().setMinimumSectionSize(37)
        self.scan_file = QtWidgets.QPushButton(CompressUI)
        self.scan_file.setGeometry(QtCore.QRect(420, 290, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scan_file.setFont(font)
        self.scan_file.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.scan_file.setObjectName("scan_file")
        self.delete_file = QtWidgets.QPushButton(CompressUI)
        self.delete_file.setGeometry(QtCore.QRect(540, 290, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_file.setFont(font)
        self.delete_file.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.delete_file.setObjectName("delete_file")
        self.comfirm_compress = QtWidgets.QPushButton(CompressUI)
        self.comfirm_compress.setGeometry(QtCore.QRect(410, 510, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comfirm_compress.setFont(font)
        self.comfirm_compress.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.comfirm_compress.setObjectName("comfirm_compress")
        self.cancel_compress = QtWidgets.QPushButton(CompressUI)
        self.cancel_compress.setGeometry(QtCore.QRect(530, 510, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_compress.setFont(font)
        self.cancel_compress.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.cancel_compress.setObjectName("cancel_compress")
        self.line = QtWidgets.QFrame(CompressUI)
        self.line.setGeometry(QtCore.QRect(30, 350, 601, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(CompressUI)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(CompressUI)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 81))
        self.widget.setStyleSheet("background-color: rgb(32, 140, 255);")
        self.widget.setObjectName("widget")
        self.btn_com = QtWidgets.QPushButton(self.widget)
        self.btn_com.setGeometry(QtCore.QRect(20, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_com.setFont(font)
        self.btn_com.setStyleSheet("border-radius:100px;")
        self.btn_com.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_com.setIcon(icon)
        self.btn_com.setIconSize(QtCore.QSize(50, 50))
        self.btn_com.setAutoRepeat(False)
        self.btn_com.setObjectName("btn_com")
        self.btn_dis = QtWidgets.QPushButton(self.widget)
        self.btn_dis.setGeometry(QtCore.QRect(120, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dis.setFont(font)
        self.btn_dis.setStyleSheet("border-radius:100px;")
        self.btn_dis.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dis.setIcon(icon1)
        self.btn_dis.setIconSize(QtCore.QSize(50, 50))
        self.btn_dis.setObjectName("btn_dis")
        self.btn_eva = QtWidgets.QPushButton(self.widget)
        self.btn_eva.setGeometry(QtCore.QRect(220, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eva.setFont(font)
        self.btn_eva.setStyleSheet("border-radius:100px;")
        self.btn_eva.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eva.setIcon(icon2)
        self.btn_eva.setIconSize(QtCore.QSize(50, 50))
        self.btn_eva.setAutoRepeat(False)
        self.btn_eva.setObjectName("btn_eva")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(110, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(210, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(CompressUI)
        self.cancel_compress.clicked.connect(CompressUI.cancel_compress)
        self.scan_file.clicked.connect(CompressUI.select_compress)
        self.delete_file.clicked.connect(CompressUI.delete_file)
        self.comfirm_compress.clicked.connect(CompressUI.confirm_compress)
        self.btn_dis.clicked.connect(CompressUI.to_decomUI)
        self.btn_eva.clicked.connect(CompressUI.to_evaUI)
        QtCore.QMetaObject.connectSlotsByName(CompressUI)

    def retranslateUi(self, CompressUI):
        _translate = QtCore.QCoreApplication.translate
        CompressUI.setWindowTitle(_translate("CompressUI", "压缩界面"))
        item = self.file_info.horizontalHeaderItem(0)
        item.setText(_translate("CompressUI", "名称"))
        item = self.file_info.horizontalHeaderItem(1)
        item.setText(_translate("CompressUI", "大小"))
        item = self.file_info.horizontalHeaderItem(2)
        item.setText(_translate("CompressUI", "路径"))
        item = self.file_info.horizontalHeaderItem(3)
        item.setText(_translate("CompressUI", "修改时间"))
        self.scan_file.setText(_translate("CompressUI", "添加"))
        self.delete_file.setText(_translate("CompressUI", "删除"))
        self.comfirm_compress.setText(_translate("CompressUI", "压缩"))
        self.cancel_compress.setText(_translate("CompressUI", "取消"))
        self.label_3.setText(_translate("CompressUI", "选择压缩文件："))
        self.label_7.setText(_translate("CompressUI", "  压缩文件"))
        self.label_8.setText(_translate("CompressUI", "解压缩文件"))
        self.label_9.setText(_translate("CompressUI", "  质量评估"))
from dcmp import picture_rc
