# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'discompress.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DiscompressUI(object):
    def setupUi(self, DiscompressUI):
        DiscompressUI.setObjectName("DiscompressUI")
        DiscompressUI.resize(659, 603)
        DiscompressUI.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.dis_progressBar = QtWidgets.QProgressBar(DiscompressUI)
        self.dis_progressBar.setGeometry(QtCore.QRect(30, 380, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dis_progressBar.setFont(font)
        self.dis_progressBar.setStyleSheet("QProgressBar::chunk { background-color: rgb(32, 140, 255) }\n"
"QProgressBar { text-align: right }")
        self.dis_progressBar.setProperty("value", 0)
        self.dis_progressBar.setObjectName("dis_progressBar")
        self.file_info = QtWidgets.QTableWidget(DiscompressUI)
        self.file_info.setGeometry(QtCore.QRect(20, 160, 611, 91))
        self.file_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_info.setLineWidth(3)
        self.file_info.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.file_info.setShowGrid(False)
        self.file_info.setRowCount(0)
        self.file_info.setObjectName("file_info")
        self.file_info.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_info.setHorizontalHeaderItem(3, item)
        self.file_info.horizontalHeader().setVisible(True)
        self.file_info.horizontalHeader().setCascadingSectionResizes(False)
        self.file_info.horizontalHeader().setDefaultSectionSize(152)
        self.file_info.horizontalHeader().setMinimumSectionSize(28)
        self.file_info.verticalHeader().setVisible(False)
        self.file_info.verticalHeader().setDefaultSectionSize(45)
        self.file_info.verticalHeader().setMinimumSectionSize(37)
        self.scan_file = QtWidgets.QPushButton(DiscompressUI)
        self.scan_file.setGeometry(QtCore.QRect(410, 270, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scan_file.setFont(font)
        self.scan_file.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.scan_file.setObjectName("scan_file")
        self.delete_file = QtWidgets.QPushButton(DiscompressUI)
        self.delete_file.setGeometry(QtCore.QRect(530, 270, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_file.setFont(font)
        self.delete_file.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.delete_file.setObjectName("delete_file")
        self.line = QtWidgets.QFrame(DiscompressUI)
        self.line.setGeometry(QtCore.QRect(30, 340, 591, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(DiscompressUI)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.comfirm_decompress = QtWidgets.QPushButton(DiscompressUI)
        self.comfirm_decompress.setGeometry(QtCore.QRect(410, 480, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comfirm_decompress.setFont(font)
        self.comfirm_decompress.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.comfirm_decompress.setObjectName("comfirm_decompress")
        self.cancel_decompress = QtWidgets.QPushButton(DiscompressUI)
        self.cancel_decompress.setGeometry(QtCore.QRect(530, 480, 93, 32))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancel_decompress.setFont(font)
        self.cancel_decompress.setStyleSheet("background-color: rgb(32, 140, 255);\n"
"color: rgb(255, 255, 255);")
        self.cancel_decompress.setObjectName("cancel_decompress")
        self.widget = QtWidgets.QWidget(DiscompressUI)
        self.widget.setGeometry(QtCore.QRect(0, 0, 661, 81))
        self.widget.setStyleSheet("background-color: rgb(32, 140, 255);")
        self.widget.setObjectName("widget")
        self.btn_com = QtWidgets.QPushButton(self.widget)
        self.btn_com.setGeometry(QtCore.QRect(20, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_com.setFont(font)
        self.btn_com.setStyleSheet("border-radius:100px;")
        self.btn_com.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_com.setIcon(icon)
        self.btn_com.setIconSize(QtCore.QSize(50, 50))
        self.btn_com.setAutoRepeat(False)
        self.btn_com.setObjectName("btn_com")
        self.btn_dis = QtWidgets.QPushButton(self.widget)
        self.btn_dis.setGeometry(QtCore.QRect(120, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dis.setFont(font)
        self.btn_dis.setStyleSheet("border-radius:100px;")
        self.btn_dis.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dis.setIcon(icon1)
        self.btn_dis.setIconSize(QtCore.QSize(50, 50))
        self.btn_dis.setObjectName("btn_dis")
        self.btn_eva = QtWidgets.QPushButton(self.widget)
        self.btn_eva.setGeometry(QtCore.QRect(220, 0, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eva.setFont(font)
        self.btn_eva.setStyleSheet("border-radius:100px;")
        self.btn_eva.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/image/12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_eva.setIcon(icon2)
        self.btn_eva.setIconSize(QtCore.QSize(50, 50))
        self.btn_eva.setAutoRepeat(False)
        self.btn_eva.setObjectName("btn_eva")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(110, 50, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(210, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"background：transparent；")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(DiscompressUI)
        self.comfirm_decompress.clicked.connect(DiscompressUI.confirm_decompress)
        self.cancel_decompress.clicked.connect(DiscompressUI.delete_decomfile)
        self.scan_file.clicked.connect(DiscompressUI.select_decomfile)
        self.delete_file.clicked.connect(DiscompressUI.delete_decomfile)
        self.btn_com.clicked.connect(DiscompressUI.to_comUI)
        self.btn_eva.clicked.connect(DiscompressUI.to_evaUI)
        QtCore.QMetaObject.connectSlotsByName(DiscompressUI)

    def retranslateUi(self, DiscompressUI):
        _translate = QtCore.QCoreApplication.translate
        DiscompressUI.setWindowTitle(_translate("DiscompressUI", "解压缩界面"))
        item = self.file_info.horizontalHeaderItem(0)
        item.setText(_translate("DiscompressUI", "名称"))
        item = self.file_info.horizontalHeaderItem(1)
        item.setText(_translate("DiscompressUI", "大小"))
        item = self.file_info.horizontalHeaderItem(2)
        item.setText(_translate("DiscompressUI", "路径"))
        item = self.file_info.horizontalHeaderItem(3)
        item.setText(_translate("DiscompressUI", "修改时间"))
        self.scan_file.setText(_translate("DiscompressUI", "添加"))
        self.delete_file.setText(_translate("DiscompressUI", "删除"))
        self.label_3.setText(_translate("DiscompressUI", "选择解压文件："))
        self.comfirm_decompress.setText(_translate("DiscompressUI", "解压缩"))
        self.cancel_decompress.setText(_translate("DiscompressUI", "取消"))
        self.label_7.setText(_translate("DiscompressUI", "  压缩文件"))
        self.label_8.setText(_translate("DiscompressUI", "解压缩文件"))
        self.label_9.setText(_translate("DiscompressUI", "  质量评估"))
from dcmp import picture_rc
